name: Houmy E2E

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select test environment'
        required: true
        default: https://www.houmy.cz
        type: choice
        options:
          - https://www.houmy.cz

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}
      CYPRESS_user_email: ${{ secrets.CYPRESS_USER_EMAIL }}
      CYPRESS_user_password: ${{ secrets.CYPRESS_USER_PASSWORD }}
      CYPRESS_wrong_password: ${{ secrets.CYPRESS_WRONG_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change to project directory
        working-directory: houmy_e2e
        run: npm install

      - name: Run Cypress tests
        working-directory: houmy_e2e
        run: npx cypress run
