name: Houmy E2E

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select test environment'
        required: true
        default: https://www.houmy.cz
        type: choice
        options:
          - https://www.houmy.cz

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      WRONG_PASSWORD: ${{ secrets.WRONG_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
